
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: code_challenge_superhero_development


test:
  <<: *default
  database: code_challenge_superhero_test


#
production:
  <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  database: code_challenge_superhero_production
  username: code_challenge_superhero
  password: <%= ENV["CODE_CHALLENGE_SUPERHERO_DATABASE_PASSWORD"] %>

# production:
#   <<: *default
#   port: 5432
# 
